"""Add shop and items

Revision ID: cb99c8eed582
Revises: 3ef7db329fcf
Create Date: 2025-10-09 14:55:06.552842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb99c8eed582'
down_revision: Union[str, Sequence[str], None] = '3ef7db329fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('store_name', sa.String(length=30), nullable=False))
    op.drop_index(op.f('name'), table_name='stores')
    op.create_unique_constraint(None, 'stores', ['store_name'])
    op.drop_column('stores', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'stores', type_='unique')
    op.create_index(op.f('name'), 'stores', ['name'], unique=True)
    op.drop_column('stores', 'store_name')
    # ### end Alembic commands ###
